#pragma once
#include "Scene.h"
#include "Mesh.h"
#include <Transform.h>
#include <UnorderedVector.h>

class MeshManager
{
private:
	static MeshManager* m_instance; 
	MeshManager();
public:
	UnorderedVector<Mesh*>  meshList;
	~MeshManager();
	static MeshManager* GetInstance();
	static void DestroyInstance();
	enum Meshes
	{
		//carnival roaming
		GEO_CIRCUSTENT,
		GEO_CIRCUSNAME,
		GEO_CANTENT,
		GEO_CANTENTROOF,
		GEO_STRIPEWALL,
		GEO_GRASS,
		GEO_TABLECAN,
		GEO_CAN,
		GEO_TOPCOTTONCANDY,
		GEO_MIDDLECOTTONCANDY,
		GEO_INNERMIDDLECOTTONCANDY,
		GEO_COTTONCANDYS,
		GEO_COTTONCANDYMACHINE,
		GEO_CARAMELAPPLE,
		GEO_CARAMELAPPLESTAND,
		GEO_BOTTOMCOTTONCANDY,
		GEO_CLOWNWORKER,
		GEO_CR_PLINKO,
		GEO_POOL,
		GEO_POOLWATER,
		GEO_DUCKY,
		GEO_SHOOTINGDUCK,
		GEO_TARGET,
		GEO_CONVEYER,
		GEO_GUN,
		GEO_BOARD,
		GEO_BALLOON,
		GEO_BOTTLES,
		GEO_RACK,
		GEO_COUNTER,
		GEO_RING,
		GEO_TICKETBOOTHFRAME,
		GEO_TICKETBOOTHBOX,
		GEO_TICKETBOOTHLIGHTS,
		GEO_TICKETBOOTHWINDOWS,
		GEO_TREE,
		GEO_FENCE,

		GEO_ENERGYFRAME, 
		GEO_ENERGYBAR, 

		//plinko
		GEO_PLINKO,
		GEO_PLINKO_BOOTHROOF,
		GEO_PLINKO_BOOTHGUARDS,

		//Can Game
		GEO_POWERUI_FRAME,
		GEO_POWERUI_BAR,

		GEO_BALL,
		GEO_CK_CAN,
		GEO_CK_TABLE,
		GEO_CK_BOOTHROOF,
		GEO_CK_BOOTHGUARDS,
		GEO_CK_COUNTER,
		GEO_LIGHTBULB,

		//ring toss
		GEO_RT_BOARD,
		GEO_RT_BOTTLE,
		GEO_RT_RING,
		GEO_RT_TIE,
		GEO_RT_PLANE,
		GEO_RT_TABLE,
		GEO_RT_TABLECLOTH,
		GEO_RT_COUNTER,
		GEO_RT_LIGHTPOLE,

		// duck shooting:
		GEO_DS_QUAD,
		GEO_DS_BOOTHROOF,
		GEO_DS_BOOTHGUARDS,
		GEO_DS_COUNTER,
		GEO_DS_LIGHTBULB,
		GEO_DS_DUCK,
		GEO_DS_GUN,
		GEO_DS_BULLET,
		GEO_DS_PILLAR,
		GEO_DS_CONVEYOR,
		GEO_DS_FAIRYLIGHT,

		NUM_MESHES
	};

	virtual void Init(); 
};